---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}${SUFFIX}-deployment-template
  annotations:
    description: Deployment template for a Schema Spy instance.
    tags: schema-spy
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}${SUFFIX}-allow-ingress
      labels:
        name: ${NAME}${SUFFIX}-allow-ingress
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow traffic from routes into the ${ROLE} container(s).
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}${SUFFIX}
          env: ${TAG_NAME}
      policyTypes:
        - Ingress

  # - kind: NetworkSecurityPolicy
  #   apiVersion: security.devops.gov.bc.ca/v1alpha1
  #   metadata:
  #     name: ${NAME}${SUFFIX}
  #     labels:
  #       name: ${NAME}${SUFFIX}
  #       app: ${APP_NAME}${SUFFIX}
  #       app-group: ${APP_GROUP}
  #       env: ${TAG_NAME}
  #   spec:
  #     description: |
  #       Allow schema spy to access the fdw database to generate the schema documentation.
  #     source:
  #       - - role=${ROLE}
  #         - app=${APP_NAME}${SUFFIX}
  #         - env=${TAG_NAME}
  #         - $namespace=${NAMESPACE}-${TAG_NAME}
  #     destination:
  #       - - role=${FDW_ROLE}
  #         - app=${APP_NAME}${SUFFIX}
  #         - env=${TAG_NAME}
  #         - $namespace=${NAMESPACE}-${TAG_NAME}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      plain-password: ${SCHEMASPY_PLAIN_PASSWORD}
      password: ${SCHEMASPY_PASSWORD}
      user: ${SCHEMASPY_USER}
    type: Opaque

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
      annotations:
        description: Exposes and load balances the application pods
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: ${NAME}${SUFFIX}

  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      host: ${APPLICATION_DOMAIN}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}

  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Defines how to deploy the container.
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}${SUFFIX}
              image:  
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
                      key: fdw-host
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
                      key: fdw-name
                - name: DATABASE_CATALOG
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
                      key: fdw-catalog
                - name: DATABASE_SCHEMA
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
                      key: fdw-schema
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
                      key: fdw-user
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${DATABASE_DEPLOYMENT_NAME}${SUFFIX}
                      key: fdw-password
                - name: DATABASE_TYPE
                  value: ${DATABASE_TYPE}
                - name: DATABASE_DRIVER
                  value: ${DATABASE_DRIVER}
                - name: SCHEMASPY_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: user
                - name: SCHEMASPY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: password
                - name: OUTPUT_PATH
                  value: ${OUTPUT_PATH}
              readinessProbe:
                timeoutSeconds: 30
                initialDelaySeconds: 3
                httpGet:
                  path: /health
                  port: 8080
              livenessProbe:
                timeoutSeconds: 30
                initialDelaySeconds: 1800
                httpGet:
                  path: /health
                  port: 8080
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              volumeMounts:
                - name: ${NAME}${SUFFIX}-config-volume
                  mountPath: ${CONFIG_MOUNT_PATH}${CONFIG_FILE_NAME}
                  subPath: ${CONFIG_FILE_NAME}
          volumes:
            - name: ${NAME}${SUFFIX}-config-volume
              configMap:
                name: ${CONFIG_MAP_NAME}${SUFFIX}
                items:
                  - key: ${CONFIG_FILE_NAME}
                    path: ${CONFIG_FILE_NAME}
parameters:
  - name: NAME
    displayName: Schema Spy Name
    description:
      The name assigned to all of the schema spy objects defined in this
      template.
    required: true
    value: schema-spy-oracle
  - name: ROLE
    displayName: Role
    description: Role
    required: true
    value: schema-spy-oracle
  - name: FDW_ROLE
    displayName: Foreign Data Wrapper Role
    description: The name given to the foreign data wrapper role.
    required: true
    value: fdw
  - name: NAMESPACE
    displayName: The target namespace for the resources.
    required: true
    value: 7cba16
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: -primary
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: BcRegistriesAgent
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: primary-instance
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description:
      The namespace of the OpenShift project containing the imagestream for
      the application.
    value: 7cba16-tools
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: schema-spy-with-oracle-jdbc
  - name: APPLICATION_DOMAIN
    displayName: Application Hostname
    description:
      The exposed hostname that will route to the service, if left blank
      a value will be defaulted.
    value: schema-spy-oracle-primary-dev.apps.silver.devops.gov.bc.ca
  - name: OUTPUT_PATH
    displayName: Output Path
    required: true
    description: The SchemSpy output path.
    value: /var/www/html/doc
  - name: SCHEMASPY_USER
    displayName: Username for the SchemaSpy Instance
    description: Username for the SchemaSpy Instance.  Needs to be base64 encoded.
    required: true
    generate: expression
    from: "[a-zA-Z_][a-zA-Z0-9_]{10}"
  - name: SCHEMASPY_PLAIN_PASSWORD
    displayName: Password for the SchemaSpy Instance
    description: Plain Text Password for the SchemaSpy Instance.
    required: true
    generate: expression
    from: "[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]{16}"
  - name: SCHEMASPY_PASSWORD
    displayName: Password for the SchemaSpy Instance
    description: Password for the SchemaSpy Instance. It is teh bse64 encoded representation of SCHEMASPY_PLAIN_PASSWORD.
    required: true
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true
  - name: DATABASE_DEPLOYMENT_NAME
    displayName: Database Deployment Name
    description:
      The name associated to the database deployment resources.  In particular,
      this is used to wrie up the credentials associated to the database.
    required: true
    value: bc-reg-fdw
  - name: DATABASE_TYPE
    displayName: Database Type
    required: true
    value: orathin
  - name: DATABASE_DRIVER
    displayName: Database Driver
    required: true
    description: The path to the JDBC driver for the database.
    value: lib/ora-jdbc.jar
  - name: CONFIG_FILE_NAME
    displayName: Config File Name
    description: The name of the configuration file.
    required: true
    value: Caddyfile
  - name: CONFIG_MAP_NAME
    displayName: Config Map Name
    description: The name of the configuration map.
    required: true
    value: schema-spy-oracle-caddy-conf
  - name: CONFIG_MOUNT_PATH
    displayName: Config Mount Path
    description: The path to use to mount the config file.
    required: true
    value: /etc/caddy/
  - name: SERVER_HOST
    displayName: Server Host
    description: The value for the server host to be replaced in the Caddyfile.
    required: true
    value: "0.0.0.0"
  - name: SERVER_PORT
    displayName: Server PORT
    description: The value for the server port to be replaced in the Caddyfile.
    required: true
    value: "8080"
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 0m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 0m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 0Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 0Mi
